name: Publish VSCode extension
on:
  push:
    branches:
      - main
    paths:
      - "syntax-highlight/vscode/**"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Build VSCode package
        working-directory: syntax-highlight/vscode
        run: vsce package

      - name: Publish to Visual Studio Marketplace
        working-directory: syntax-highlight/vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish
