name: Publish VSCode extension
on:
  push:
    branches:
      - main
    paths:
      - "syntax-highlight/vscode/**"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: syntax-highlight/vscode

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Check if version exists
        id: version_check
        run: |
          VERSION=$(node -p "require('./package.json').version")
          PUBLISHED=$(npx vsce show freedev.mya-syntax | grep -qE "Version:\s+$VERSION" && echo "true" || echo "false")
          echo "version_exists=$PUBLISHED" >> $GITHUB_ENV

      - name: Build VSCode package
        if: env.version_exists == 'false'
        run: vsce package

      - name: Publish to Visual Studio Marketplace
        if: env.version_exists == 'false'
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish
